# Generated by Django 3.1.1 on 2020-09-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='status',
            field=models.CharField(choices=[('STICK', 'Stick'), ('MISSING', 'Missing'), ('FAILED', 'Failed')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='unit',
            name='type',
            field=models.CharField(choices=[('ARKLE', 'Arkle'), ('DENMAN', 'Denman'), ('KAUTO', 'Kauto'), ('WINX', 'Winx'), ('FRANKEL', 'Frankel'), ('ENABLE', 'Enable')], default='WINX', max_length=10),
        ),
    ]
