# Generated by Django 3.1.1 on 2020-09-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_logs', '0003_auto_20200923_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='status',
            field=models.CharField(choices=[('STICK', 'Stick'), ('MISSING', 'Missing'), ('FAILED', 'Failed')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='unit',
            name='type',
            field=models.CharField(choices=[('WINX', 'Winx'), ('DENMAN', 'Denman'), ('ARKLE', 'Arkle'), ('ENABLE', 'Enable'), ('FRANKEL', 'Frankel'), ('KAUTO', 'Kauto')], default='WINX', max_length=10),
        ),
    ]
