# Generated by Django 3.1.1 on 2020-09-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_logs', '0004_auto_20200923_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='type',
            field=models.CharField(choices=[('ARKLE', 'Arkle'), ('FRANKEL', 'Frankel'), ('KAUTO', 'Kauto'), ('DENMAN', 'Denman'), ('WINX', 'Winx'), ('ENABLE', 'Enable')], default='WINX', max_length=10),
        ),
    ]
