# Generated by Django 3.1.1 on 2020-09-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_logs', '0005_auto_20200923_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='status',
            field=models.CharField(choices=[('STICK', 'Stick'), ('FAILED', 'Failed'), ('MISSING', 'Missing')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='unit',
            name='type',
            field=models.CharField(choices=[('WINX', 'Winx'), ('ENABLE', 'Enable'), ('DENMAN', 'Denman'), ('ARKLE', 'Arkle'), ('KAUTO', 'Kauto'), ('FRANKEL', 'Frankel')], default='WINX', max_length=10),
        ),
    ]
