# Generated by Django 3.1.1 on 2020-09-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_logs', '0007_auto_20200923_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='status',
            field=models.CharField(choices=[('MISSING', 'Missing'), ('STICK', 'Stick'), ('FAILED', 'Failed')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='unit',
            name='type',
            field=models.CharField(choices=[('W', 'Winx'), ('D', 'Denman'), ('E', 'Enable'), ('F', 'Frankel'), ('A', 'Arkle'), ('K', 'Kauto')], default='W', max_length=10),
        ),
    ]
