# Generated by Django 3.1.1 on 2020-09-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_logs', '0008_auto_20200923_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='date_added',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='unit',
            name='status',
            field=models.CharField(choices=[('FAILED', 'Failed'), ('STICK', 'Stick'), ('MISSING', 'Missing')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='unit',
            name='type',
            field=models.CharField(choices=[('W', 'Winx'), ('F', 'Frankel'), ('D', 'Denman'), ('E', 'Enable'), ('K', 'Kauto'), ('A', 'Arkle')], default='W', max_length=10),
        ),
    ]
