# Generated by Django 3.1.1 on 2020-09-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_logs', '0009_auto_20200923_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='status',
            field=models.CharField(choices=[('FAILED', 'Failed'), ('MISSING', 'Missing'), ('STICK', 'Stick')], default='STICK', max_length=10),
        ),
        migrations.AlterField(
            model_name='unit',
            name='type',
            field=models.CharField(choices=[('A', 'Arkle'), ('F', 'Frankel'), ('D', 'Denman'), ('E', 'Enable'), ('K', 'Kauto'), ('W', 'Winx')], default='W', max_length=10),
        ),
    ]
